INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_BACKSCATTER_DECODER backscatter_decoder)

FIND_PATH(
    BACKSCATTER_DECODER_INCLUDE_DIRS
    NAMES backscatter_decoder/api.h
    HINTS $ENV{BACKSCATTER_DECODER_DIR}/include
        ${PC_BACKSCATTER_DECODER_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    BACKSCATTER_DECODER_LIBRARIES
    NAMES gnuradio-backscatter_decoder
    HINTS $ENV{BACKSCATTER_DECODER_DIR}/lib
        ${PC_BACKSCATTER_DECODER_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BACKSCATTER_DECODER DEFAULT_MSG BACKSCATTER_DECODER_LIBRARIES BACKSCATTER_DECODER_INCLUDE_DIRS)
MARK_AS_ADVANCED(BACKSCATTER_DECODER_LIBRARIES BACKSCATTER_DECODER_INCLUDE_DIRS)

